### ISSUE TITLE
[Feature Request] 专任教师培训覆盖率&培训学时与工作量&培训反馈导出

### ISSUE THREAD

**Issue by Spground** [DLUT-SIE/TMSFTT-BE#176]
**Please describe the problem you want to solve.**

院系管理员以及校级管理员，可以导出指定培训项目在指定时间段内的教师覆盖率、培训学时与工作量以及培训反馈信息。

**Describe the solution you'd like**
  
由于数据是统一的，只是前端表现形式不同（表和图@oosprey） ， 因此封装成单独的服务。

管理员可以指定
- 培训项目ID（未指定则导出所有培训项目）
- 时间段 （未指定则为最近一年）

**Additional context**

无

**Comment by Time1ess** [comment]
Exporting statistics for specific department should also be supported.
